apiVersion: v1
kind: Service
metadata:
  name: tournament-service
spec:
  type: NodePort
  selector:
    app: tournament-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7006
      nodePort: 30080    # (optional) NodePort range is 30000–32767