apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  type: NodePort
  selector:
    app: auth-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7004
      nodePort: 30080    # (optional) NodePort range is 30000–32767