apiVersion: v1
kind: Service
metadata:
  name: venue-service
spec:
  type: NodePort
  selector:
    app: venue-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7008
      nodePort: 30080    # (optional) NodePort range is 30000–32767