apiVersion: apps/v1   #version of the API used to create the deployment
kind: Deployment      # Deployment resource type
metadata:             
    name: scoring-service
    labels:   
     app: scoring-service
     tier: backend
     environment: production
spec:                 #specification of the desired state
  replicas: 1         #Number of pods copies
  selector:           # tell deployment which Pods it manages(by labels)
    matchLabels:
      app: scoring-service
  template:            #Pod definition
    metadata:
      labels:          # labes for pods
        app: scoring-service
        tier: backend
        environment: staging
    spec:
      containers:
        - name: scoring-service
          image: ustaadlokk/scoring-service # Use your real Docker Hub image/tag
          imagePullPolicy: Always
          ports:
            - containerPort: 7003
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: 7003
            initialDelaySeconds: 10
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 7003
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 2
      restartPolicy: Always