apiVersion: v1
kind: Service
metadata:
  name: scoring-service
spec:
  type: NodePort
  selector:
    app: scoring-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7003
      nodePort: 30080    # (optional) NodePort range is 30000–32767