const { z } = require("zod");

const FixtureInputValidator = z.object({
    tournamentId: z.string().min(1),
    fixtures: z.object({
        tournamentFormat: z.enum(["single_elimination", "round_robin"]),
        numGroups: z.string().optional(),
        autoGenerateDates: z.string().optional(),
        randomize: z.boolean(),
        allowByes: z.boolean(),
        startDate: z.string(),
        matchesPerDay: z.number().optional(),
    })
});

module.exports = {
    FixtureInputValidator
};
