apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  type: NodePort
  selector:
    app: notification-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7002
      nodePort: 30080    # (optional) NodePort range is 30000–32767