apiVersion: v1
kind: Service
metadata:
  name: team-service
spec:
  type: NodePort
  selector:
    app: team-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7005
      nodePort: 30080    # (optional) NodePort range is 30000–32767